AWS infrastructure to handle radius tracker logic
rangle/radius-tracker pull request #13
Opened 2022-04-11 08:39 UTC by pablospaniard

- API gateway
- Lambda listener
- Lambda worker
- SNS
- SQS
- S3 bucket
- Terraform back up on AWS

2022-04-14 14:24 UTC, pablospaniard commented on .eslintrc.js
> +        "indent": ["error", 4, { "SwitchCase": 1 , "flatTernaryExpressions": false }],
sorry, had to change that, otherwise my IDE can't work :(

2022-04-15 08:44 UTC, pablospaniard commented on terraform/main.tf
> +  profile = "radius-tracker"
for testing purposes, you can create cli credentials and put them into `radius-tracker` profile inside `~/.aws/credentials` file, or I can create credentials for you (ping me if you need them). After we replace those credentials with Rangle's.

2022-04-19 11:08 UTC, smoogly requested changes

2022-04-19 11:08 UTC, smoogly commented on terraform/main.tf
> +    allowed_origins = ["*"]
I would prefer to specify a concrete origin. I don't think it's particularly dangerous to have a `*` here, but I feel a specific origin is better as a matter of best practice.

2022-04-19 11:08 UTC, smoogly commented on terraform/main.tf
> +        "Principal": "*",
This should be limited to the specific lambdas.

2022-04-19 11:08 UTC, smoogly commented on terraform/state-backup.tf
> +    bucket  = "radius-tracker"
There's a `radius-tracker` bucket defined as a resource. I don't think it's a good idea to let terraform manage the same bucket it uses for storing configuration.

2022-04-19 11:08 UTC, smoogly commented on terraform/worker/main.tf
> +resource "aws_iam_role_policy" "save_result_objest" {
Typo
```suggestion
resource "aws_iam_role_policy" "save_result_object" {
```

2022-04-19 11:08 UTC, smoogly commented on terraform/zip.tf
> +}
Similar to comments above, this section would be simpler if lambdas were built to a separate directory, rather than in-place to the same folder.

2022-04-21 13:03 UTC, pablospaniard commented on src/demo/src/analysis/Analysis.tsx
> +            return <Results data={ analysis } />;
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/10797797/164463947-a2693a36-2e79-4372-a20a-b6626dedd30c.png">

2022-05-18 14:52 UTC, smoogly requested changes

2022-05-18 14:52 UTC, smoogly commented on src/lambda/worker/handler.spec.ts
> +        s3Client.send = jest.fn().mockReturnValue(true),
`send` is asynchronous, so I believe the `mockResolvedValue` should be used instead:
```suggestion
        s3Client.send = jest.fn().mockResolvedValue(true),
```

This makes little difference for the code as written, but preserves the method signature.

2022-05-18 14:52 UTC, smoogly commented on src/lambda/worker/index.ts
> +        "SNS_ARN",
Look like worker doesn't need `SNS_ARN`
```suggestion
```

2022-05-18 14:52 UTC, smoogly commented on src/lambda/listener/index.ts
> +    new S3Client({ region: process.env.REGION }),
For robustness, gotta check that `REGION` env is set.

2022-05-19 16:31 UTC, smoogly approved these changes
🚀 looks good!

2022-05-20 07:46 UTC, merged